#!/bin/bash

#PBS -N my_simulations
#PBS -l mem=6gb
#PBS -l walltime=11:59:59
#PBS -J 251
#PBS -o logs/${PBS_JOBID}.out
#PBS -e logs/${PBS_JOBID}.err
#PBS -j oe

cd $PBS_O_WORKDIR

module purge
module add r/4.5.1

echo "Job started: $PBS_JOBID"
echo "Array index: $PBS_ARRAY_INDEX"

PARAM_FILE=config/params.csv

LINE=$(sed -n "${PBS_ARRAY_INDEX}p" $PARAM_FILE)

IFS=',' read family signal r c_val sigma2 globalTest p nsim seed <<< "$LINE"

echo "Parameters:"
echo "$LINE"

Rscript scripts/main_Test_Katana.R \
  $family \
  $signal \
  $r \
  $c_val \
  $sigma2 \
  $globalTest \
  $p \
  $nsim \
  $seed

echo "Job finished"