#!/bin/bash
#PBS -N rerun_failed
#PBS -l mem=32gb
#PBS -l walltime=11:59:59
#PBS -J 1-41
#PBS -o logs/
#PBS -e logs/
#PBS -j oe

cd "$PBS_O_WORKDIR"

module purge
module load r/4.5.1

BASE_SEED=1000

job_id=$(sed -n "${PBS_ARRAY_INDEX}p" slurm/failed_41jobs.txt)

SEED=$((BASE_SEED + job_id - 1))

echo "Original job ID = ${job_id}"
echo "Seed = ${SEED}"

Rscript scripts/main_Test_Katana.R "${SEED}"